'use client';
import { useState, useEffect } from 'react';
import { supabase } from '@/lib/supabase';

export default function TeacherAssessmentsPage() {
  const [showCreate, setShowCreate] = useState(false);
  const [assessments, setAssessments] = useState<any[]>([]);

  useEffect(() => {
    const fetchAssessments = async () => {
      // Fetch actual lessons to act as assessments (since each lesson has an AI quiz)
      const { data } = await supabase.from('lessons').select('*').order('created_at', { ascending: false });
      if (data) {
        setAssessments(data.map((l: any) => ({
          title: l.title + ' Quiz',
          subject: l.subject,
          grade: l.grade,
          questions: 5, // generated by AI
          submissions: l.view_count || 0,
          avgScore: Math.floor(Math.random() * 20) + 70, // Simulated score for UI
          status: l.processing_status === 'completed' ? 'active' : 'draft'
        })));
      }
    };
    fetchAssessments();
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-white">Assessments</h1>
          <p className="text-white/60 mt-1">Create and manage quizzes for your students</p>
        </div>
        <button onClick={() => setShowCreate(!showCreate)} className="px-6 py-3 bg-gradient-to-r from-[#6C63FF] to-[#00C9A7] text-white font-semibold rounded-xl hover:opacity-90 transition">
          + Create Assessment
        </button>
      </div>

      {showCreate && (
        <div className="glass-card p-6 border border-[#6C63FF]/30">
          <h3 className="text-white font-semibold mb-4">New Assessment</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="text-white/80 text-sm mb-1 block">Title</label>
              <input className="glass-input w-full" placeholder="Quiz title" />
            </div>
            <div>
              <label className="text-white/80 text-sm mb-1 block">Linked Lesson</label>
              <select className="glass-input w-full bg-transparent appearance-none">
                <option className="bg-[#24243e]">Structure of Atom</option>
                <option className="bg-[#24243e]">Linear Equations</option>
              </select>
            </div>
            <div>
              <label className="text-white/80 text-sm mb-1 block">Time Limit (minutes)</label>
              <input type="number" className="glass-input w-full" defaultValue={15} />
            </div>
            <div>
              <label className="text-white/80 text-sm mb-1 block">Passing Score (%)</label>
              <input type="number" className="glass-input w-full" defaultValue={60} />
            </div>
          </div>

          <h4 className="text-white/80 text-sm font-medium mt-6 mb-3">Questions</h4>
          <div className="space-y-4">
            {[1, 2].map(q => (
              <div key={q} className="bg-white/5 rounded-xl p-4 border border-white/5">
                <input className="glass-input w-full mb-3 text-sm" placeholder={`Question ${q}`} />
                <div className="grid grid-cols-2 gap-2">
                  {['A', 'B', 'C', 'D'].map(opt => (
                    <div key={opt} className="flex items-center gap-2">
                      <input type="radio" name={`correct-${q}`} className="accent-[#6C63FF]" />
                      <input className="glass-input flex-1 text-sm py-1.5" placeholder={`Option ${opt}`} />
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
          <div className="flex gap-3 mt-4">
            <button className="px-4 py-2 bg-white/5 text-white/60 rounded-xl text-sm hover:bg-white/10 transition">+ Add Question</button>
            <div className="flex-1" />
            <button onClick={() => setShowCreate(false)} className="px-4 py-2 bg-white/10 text-white rounded-xl text-sm hover:bg-white/20 transition">Cancel</button>
            <button className="px-6 py-2 bg-gradient-to-r from-[#6C63FF] to-[#00C9A7] text-white font-semibold rounded-xl hover:opacity-90 transition text-sm">Publish</button>
          </div>
        </div>
      )}

      {/* Assessments Table */}
      <div className="glass-card overflow-hidden">
        <table className="w-full text-left">
          <thead className="bg-white/5 text-white/50 text-xs uppercase tracking-wider">
            <tr>
              <th className="p-4 font-medium">Assessment</th>
              <th className="p-4 font-medium">Subject</th>
              <th className="p-4 font-medium">Questions</th>
              <th className="p-4 font-medium">Submissions</th>
              <th className="p-4 font-medium">Avg Score</th>
              <th className="p-4 font-medium">Status</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-white/5 text-sm">
            {assessments.map((a, i) => (
              <tr key={i} className="hover:bg-white/5">
                <td className="p-4 text-white font-medium">{a.title}</td>
                <td className="p-4 text-white/70">{a.subject} • Grade {a.grade}</td>
                <td className="p-4 text-white/70">{a.questions}</td>
                <td className="p-4 text-white/70">{a.submissions}</td>
                <td className="p-4"><span className={`font-medium ${a.avgScore >= 75 ? 'text-[#00C9A7]' : 'text-yellow-400'}`}>{a.avgScore}%</span></td>
                <td className="p-4"><span className={`px-2 py-1 rounded-full text-[10px] font-medium ${a.status === 'active' ? 'bg-green-500/20 text-green-400' : 'bg-white/10 text-white/40'}`}>{a.status}</span></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
